### ISSUE TITLE
SMPL annotation

### ISSUE THREAD

**Issue by chenmingTHU** [sha2nkt/moyo_toolkit#1]
Thank you for your excellent work! Can you offer the downloading scripts for SMPL annotations? Thank you~

**Comment by tszhang97** [comment]
Another question, what's the fps of the smpl parameters in the pkl file? According to the sup. , image fps is 30, however, when I save smpl to bvh file, 60 fps file is more reasonable. For example,  "220923_yogi_body_hands_03596_Boat_Pose_or_Paripurna_Navasana_-a_stageii.pkl" the length of pp_params['fullpose'] is 892, I save it with 30 and 60 fps, 60fps looks  more reasonable.
![image](https://github.com/sha2nkt/moyo_toolkit/assets/39046939/b9fe5c6c-e991-4bf8-baa9-728fcad3d265)

**Comment by yufu-liu** [comment]
Hi, @tszhang97 

Maybe I can answer your question. I found there is a framerate label in every data file (.pkl), and it shows the frame rate of data is 60 Hz.

**Comment by yufu-liu** [comment]
By the way, I have another question about the beta of smpl data. 
Why are they all set to zero?

**Comment by oscarfossey** [comment]
Thank you for your excellent work! Do you now the coordinate system of the translations? Are they in camera frame or in world frame? Which dimensions is the up vector?

**Comment by sha2nkt** [comment]
> Thank you for your excellent work! Can you offer the downloading scripts for SMPL annotations? Thank you~

We have updated the README to provide the SMPL fits to the MOYO data

**Comment by sha2nkt** [comment]
> Another question, what's the fps of the smpl parameters in the pkl file? According to the sup. , image fps is 30, however, when I save smpl to bvh file, 60 fps file is more reasonable. For example, "220923_yogi_body_hands_03596_Boat_Pose_or_Paripurna_Navasana_-a_stageii.pkl" the length of pp_params['fullpose'] is 892, I save it with 30 and 60 fps, 60fps looks more reasonable. ![image](https://user-images.githubusercontent.com/39046939/269233257-b9fe5c6c-e991-4bf8-baa9-728fcad3d265.png)

The RGB images are captured at 30 fps while the SMPLX fits are captured at 60 fps

**Comment by sha2nkt** [comment]
FYI, we released the AMASS format data
