### ISSUE TITLE
Image example and compressed videos?

### ISSUE THREAD

**Issue by zehongs** [sha2nkt/moyo_toolkit#12]
Hi @sha2nkt . Thanks for  your awesome work on this project.
I was wondering if you could provide some full-resolution image examples. Downloading 700GB of data is quite a challenge.
Also, is it possible to provide compressed videos? Here’s a code snippet that might help:
```python
def save_video(images, video_path, fps=30, quality=6):
    images = np.array(images)

    # remove right-bottom to make sure the size is multiple of 16
    H, W = images[0].shape[:2]
    H = H // 16 * 16
    W = W // 16 * 16
    images = images[:, :H, :W, :]  # Do not change left-upper corner

    # Save to target
    imageio.mimsave(video_path, images, fps=fps, quality=quality)
```
We’re looking to test our pose estimator’s MPJPE using RGB and GT, similar to Table 2 in your paper. Could you let us know which specific data sequences were used for this test?
Thanks a lot!

**Comment by sha2nkt** [comment]
We provide a list of zips for every pose sequence separately. Please feel free to modify [this](https://github.com/sha2nkt/moyo_toolkit/blob/master/moyo/bash/assets/urls/images_train.txt) or [this](https://github.com/sha2nkt/moyo_toolkit/blob/master/moyo/bash/assets/urls/images_val.txt) file to only download a single image folder for particular pose sequences. There is no need to download the full dataset this way. 

We already provide downsampled 2k images from the original 4k capture. Note that the person only occupies about 25-40% of the pixels in every frame, so downsampling further may not be a good idea. 

About your last question, Table 2 contains results from an outdated version of MOYO which was smaller and different than the released version. As you can see in Fig 5, out subject wore a black mocap suit while in the released version, the subject is in regular clothes. I would advice you to please use the release MOYO dataset and report results on the released version.
