### ISSUE TITLE
SMPLX and keypoints annotation seems not in same coordinate

### ISSUE THREAD

**Issue by Wei-Chen-hub** [sha2nkt/moyo_toolkit#3]
Thanks for releasing this amazing dataset!

I am currently visualizing moyo dataset, the keypoints projection works fine, but SMPLX seems not in the same coordinate system (when I regress the 3d SMPLX keypoints from ".pkl" annotations). Could you share some insights of how to project SMPLX on image or which coordinate system is used for SMPLX?

**Comment by sha2nkt** [comment]
We provide a [script](https://github.com/sha2nkt/moyo_toolkit#projecting-marker-on-the-image) to project markers on the image. Since SMPL-X vertices are fit to the markers, they reside in the same coordinate systems. Hence, the same script can be used to project SMPL-X vertices instead of markers.
