### ISSUE TITLE
Betas in MOYO

### ISSUE THREAD

**Issue by yufu-liu** [sha2nkt/moyo_toolkit#4]
Hi, thanks for sharing this promising dataset.

I have downloaded this dataset, but I found the betas of the data are zeros.
So I want to use MoSh to the .c3d files, and an error that the markerset is empty showed up.
I found the 'LABELS' in the .c3d files are all numbers, like '*1', '*2', '*3'..etc.

Therefore, I have two questions.
1. What is the meaning of the labels in data? 
2. Is it possible to transfer those labels to correct labels like other .c3d file in AMASS dataset?
It should have indices which correspond to certain locations on a human body.

**Comment by sha2nkt** [comment]
Hi, 
You can refer to [this](https://github.com/sha2nkt/moyo_toolkit/blob/master/moyo/utils/pressure_map_evaluation.py#L177) code where we obtain the SMPLX mesh from the parameters in MOYO. Note that we use the body V_template instead of shape parameters which tend to give a more accurate body shape.

**Comment by yufu-liu** [comment]
Hi!
Thanks for answering this issue and letting me the news!
I successfully used the function to get mesh (vertices) and look forward to the AMASS format!

**Comment by sha2nkt** [comment]
FYI, we released the AMASS format data

**Comment by yufu-liu** [comment]
Hi, Thanks for your release and update!

I just downloaded the data in SMPLH_NEUTRAL format and read it.
May I ask a question about the meaning of the betas in MOYO dataset?
To my understanding, betas in SMPLH are 16 parameters. Why does their shape equal to 300?

**Comment by sha2nkt** [comment]
The full shape space of the SMPL/SMPLH/SMPLX models consists of 300 principal components. The "later" PCs model finer shape variance. However, if you want to use 10 or 16 shape parameters, feel free to sample the "first" 10 or "first" 16 parameters respectively.

**Comment by yufu-liu** [comment]
Got it! I really appreciate your fast reply and detailed explanation!
