### ISSUE TITLE
get CoM by SMPL and SMPLX

### ISSUE THREAD

**Issue by yufu-liu** [sha2nkt/moyo_toolkit#6]
Hi, 
I have done an experiment using the function **evaluate_com** to calculate CoM on MOYO dataset by loading SMPLX and SMPL models separately and changing HDfier's model type.

I found using SMPLX was more accurate than using SMPL, especially on y-axis. 
Take an example as below: 
Ground truth: (0.6728, 0.9324, 0.9914)
SMPLX result: (0.6971, 0.9427, 1.0439)
SMPL result:   (0.6775, 1.2911, 1.0246)

So I am wondering that does this result make sense? I know the number of vertices are 6890 and 10475. Is it possible that number of vertices makes the volume different, and then leads to unsimilar CoMs?

**Comment by yufu-liu** [comment]
After thinking for a while, I guess the result was caused by difference of betas. When trying to use SMPL to calculate CoM, I set betas as zeros. For SMPLX, I use V-template.

**Comment by sha2nkt** [comment]
Yes, shape would considerably change the position of the CoM. I am glad you found it.
