### ISSUE TITLE
Neck pose of mosh_smpl label

### ISSUE THREAD

**Issue by linjing7** [sha2nkt/moyo_toolkit#9]
Hi, thanks for your excellent work! I visualize the SMPL label and it seems that the neck poses are static and not very accurate. I'm wondering if you have observed this problem?

**Comment by sha2nkt** [comment]
Hi, we haven’t noticed this. Is this issue in all sequences? Could you share some images and details on which particular files have this issue?

**Comment by linjing7** [comment]
Hi, I think there exist problems in most of the sequences, but there might be something wrong from my side. Here is a visualization result of `220926_yogi_body_hands_03596_Supported_Headstand_pose_or_Salamba_Sirsasana_-a`. I visualize the mosh_smpl label with neutral gender.
<img width="1019" alt="image" src="https://github.com/sha2nkt/moyo_toolkit/assets/70081899/9a6b4a5a-6f40-4ef6-bb5e-173abad310ad">

**Comment by sha2nkt** [comment]
I haven't rendered smpl for this sequence but I have the following smplx render and that looks fine. We just used the [smpl to smplx conversion script](https://github.com/vchoutas/smplx/blob/main/transfer_model/README.md#smpl-x-to-smpl) on this sequence to get the smpl params. Do you also face an issue when you render the SMPL-X params? 

https://github.com/sha2nkt/moyo_toolkit/assets/34213114/14a6a9ea-e489-43e3-8c15-5120e05f30f9
